version : "3.9"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: hh
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    ports:
      - 8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db:
